name: Browser Global Check

on:
  workflow_dispatch:

jobs:
  run-browser-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          #cache: 'npm' # Speeds up subsequent runs

      - name: Install Dependecies
        run: npm install

      - name: Execute Script
        run: node run check-globals
